# Lang
language: en

# Header
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives
rss: /atom.xml

# Content
fancybox: true


# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
