# Lang
language: en

# Header
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: bottom
widgets:
- category
- tagcloud
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
